# fly.toml app configuration file
app = 'multinegociobaboons-fly'
primary_region = 'eze'

[build]
  # ✨ --- LÍNEA CLAVE AÑADIDA --- ✨
  # Esto le dice a Fly.io que use su sistema moderno para detectar automáticamente Python.
  builder = "paketobuildpacks/builder-jammy-base"

  # Le decimos que compile Python desde cero para evitar errores
  [build.args]
    PYTHON_COMPILE = "1"
  
  # Le decimos que use un servidor de construcción pequeño
  [build.vm]
    cpu_kind = "shared"
    cpus = 1
    memory_mb = 2048

# Esta sección define cómo se ejecuta tu aplicación
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# Esta sección define el tamaño de la máquina que ejecuta tu app
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1