# fly.toml app configuration file
app = 'multinegociobaboons-fly'
primary_region = 'gru'

[build]
  dockerfile = "Dockerfile"  # Cambia esto para usar Docker

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "club_storage"
  destination = "/app/app/static/img/premios"
