name: Fly Deploy

on:
  push:
    branches:
      - main # Se activa solo cuando haces push a la rama 'main'

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      # 1. Descarga tu código del repositorio
      - uses: actions/checkout@v4
      
      # 2. Instala la herramienta de línea de comandos de Fly.io (flyctl)
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      # 3. Ejecuta el comando de despliegue
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}